# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image_path',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
