# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0002_neighbourhood_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('business_name', models.CharField(max_length=32)),
                ('business_email', models.EmailField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.NeighbourHood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
